tataratat/splinepy

- splinepy/io/json.py
- splinepy/load.py
> Fix json io

- splinepy/_spline.py
That's it, there is not much more to say about it
> Mini PR to add knot-vector-function

- splinepy/_spline.py
@clemens.fricke pointed out a typo that lead to a bug when normalizing knot-vectors.
It was but a stupid mistake
> Normalize knot_vectors

- splinepy/_spline.py
- tests/test_normalize_knot_vectors.py
Minor fix of `normalize_knot_vectors()` and adds unittest for it
> minor fix normalize kv and add test

- tests/common.py
- tests/test_evaluation.py
- tests/test_initialization.py
- tests/test_kv_manipulation.py
- tests/test_order_manipulation.py
New rebased pull request for #28 after incorporating the requested changes.
> Ft unittest rebase

- splinepy/_spline.py
`reduced` variable was not returned by `reduce_degrees()` function.
> Reduce Degrees had no return type

- splinepy/_spline.py
- `knot_vector_bounds` renamed to `parametric_bounds` -> now it makes sense to use this for Beziers
- extend knot_vector checks
> add parametric_bounds

- MANIFEST.in
- pyproject.toml
- setup.py
- splinepy/_base.py
- splinepy/_spline.py
- splinepy/bezier.py
- splinepy/bspline.py
- splinepy/io/json.py
- splinepy/log.py
- splinepy/nurbs.py
- splinepy/rational_bezier.py
- splinepy/utils.py
> T h 1 (re)

- cpp/splinepy/proximity/proximity.hpp
- cpp/splinepy/splines/helpers/extract.hpp
Very tiny PR, only some added braces to not confuse the compiler
> Just some initializations

- cpp/splinepy/py/py_spline.hpp
- cpp/splinepy/splines/bezier.hpp
- cpp/splinepy/splines/bspline.hpp
- cpp/splinepy/splines/helpers/extract.hpp
- cpp/splinepy/splines/nurbs.hpp
- cpp/splinepy/splines/rational_bezier.hpp
- cpp/splinepy/splines/splinepy_base.cpp
- cpp/splinepy/splines/splinepy_base.hpp
- splinepy/multipatch.py
- splinepy/spline.py
- tests/test_gismo.py
- tests/test_multipatch.py
Reorder according to #78 
*  #78
> Code refactoring and boundary renumbering

- .github/workflows/main.yml
- .github/workflows/test.yml
- .github/workflows/test_full.yml
- README.md
- setup.py
> Readme and setup

- splinepy/io/gismo.py
- splinepy/multipatch.py
- tests/test_gismo.py
Cosmetic changes and some enumeration issues. I tested 2D splines in Gismo for reference. 3D tests will be added with the boundary identification PR.
Request fast review, if possible, thx
> Bugfix in Gismo Export

- .github/workflows/main.yml
- MANIFEST.in
> Source dist

- cpp/splinepy/py/py_spline.hpp
- splinepy/spline.py
Moved the meshgrid code to cpp file
> Moved meshing of abscissae to cpp

- docs/requirements.txt
- docs/source/conf.py
Change doc style to pydata and add new extension for equations
> Change Doc Style

- cpp/splinepy/py/CMakeLists.txt
- cpp/splinepy/py/init/spline_list.cpp
- cpp/splinepy/py/py_spline.hpp
- cpp/splinepy/py/py_spline_list.hpp
- cpp/splinepy/py/splinepy_core.cpp
- tests/test_spline_list.py
List like wrapping of cpp vector of splines. Almost last step of preparations for PyMultiPatch 
*  easy access of many splines from cpp side
> add SplineList

- .pre-commit-config.yaml
- splinepy/helpme/mapper.py
- tests/test_mapping.py
> Some tests failed - hope this helps

- docs/source/index.rst
- splinepy/bezier.py
- splinepy/bspline.py
- splinepy/nurbs.py
- splinepy/rational_bezier.py
- splinepy/spline.py
Started to adapt the spline documentation. 
*  #132
> WIP: Extend spline documentation

- cpp/splinepy/py/py_spline_list.hpp
- cpp/splinepy/splines/helpers/properties.hpp
- cpp/splinepy/splines/splinepy_base.cpp
> Cu supress warning

- splinepy/io/gismo.py
- splinepy/multipatch.py
Add fields any number of fields to Multipatch, to facilitate export.
tbd
> Add Fields to Multipatch

- examples/show_microstructures.py
- splinepy/helpme/create.py
- splinepy/microstructure/microstructure.py
- splinepy/microstructure/tiles/__init__.py
- splinepy/microstructure/tiles/armadillo.py
- splinepy/microstructure/tiles/crossednuttile2d.py
- splinepy/microstructure/tiles/crosstile2d.py
- splinepy/microstructure/tiles/crosstile3d.py
- splinepy/microstructure/tiles/cube3d.py
- splinepy/microstructure/tiles/cubevoid.py
- splinepy/microstructure/tiles/double_lattice_tile.py
- splinepy/microstructure/tiles/ellipsvoid.py
- splinepy/microstructure/tiles/inversecrosstile3d.py
- splinepy/microstructure/tiles/nuttile2d.py
- splinepy/microstructure/tiles/nuttile3d.py
- splinepy/microstructure/tiles/snappytile.py
- splinepy/microstructure/tiles/tilebase.py
Added the files that are originally from microstructure derivative
> New branch for @j042 - RIP gustaf

- splinepy/bspline.py
- tests/test_composition_sensitivities.py
> Minor bugfix and new test

- .github/workflows/docs.yml
- .github/workflows/test.yml
- .github/workflows/test_full.yml
- pyproject.toml
- setup.py
use `unittest` to run tests. were using pytest just to run all the tests with one command.
> use unittest

- tests/common.py
- tests/test_bezier_extraction.py
- tests/test_c_contiguous.py
- tests/test_composition_sensitivities.py
- tests/test_creator.py
- tests/test_evaluation.py
- tests/test_greville.py
- tests/test_irit_io.py
- tests/test_kv_manipulation.py
- tests/test_normalize_knot_vectors.py
- tests/test_order_manipulation.py
- tests/test_permute_parametric_axes.py
- tests/test_property_modification.py
- tests/test_proximity.py
- tests/test_spline_type_conversion.py
To make the test case easier to read, a general test case for splines was created inside the common.py file, which has a set of splines. Furthermore, some functions have been renamed to make the code cleaner.    
```
pytest tests/ --verbose
```
> Add Base Spline Testcase 

- .pre-commit-config.yaml
- splinepy/helpme/create.py
- splinepy/utils/data.py
uses ruff instead of flake8. It is fast.
> use ruff and update changes

- splinepy/microstructure/tiles/crosstile3d.py
- splinepy/microstructure/tiles/inversecrosstile3d.py
Was broken.
Fix #188 
Derivatives pending for many tiles
> Crosstile and Inverse

- splinepy/io/mfem.py
this PR removes `mfem_index_mapping` and adds `dof_mapping` instead. This supports both 2d and 3d using `multi_index`
*  3d missing
* tests - io round trip
* extend io for 3d single patch
* multi patch load
> add mfem dof_mapping

- splinepy/io/mfem.py
we don't want to export __repr__ of KnotVector
> turn knot vectors to true list before export

- examples/iga/collocation_laplace_problem_sparse.py
Same example, but with sparse matrix. Seems to be 2-3 times faster. I've tried some other variants to set zeros, but nothing seems to be beat simple 0 multiplication.
> add same example using sparse matrix

- splinepy/io/gismo.py
- src/py/py_multipatch.cpp
2 issues:
1. wrong order of arguments in pyMultipatch constructor
2. add fields in gismo output was still expecting lists of lists
> Bugfix - Multipatch

- examples/show_isophotes_and_curvature.py
- Demonstrate more of the `show_options`
- Bragging rights for splinepy
- Fancy graphics
...
This is a possible outcome:
1. Isophotes
2. Gaussian Curvature
3. Mean Curvature
For the given spline
> New Example (fancy?)

- splinepy/spline.py
- src/py/py_knot_vector.cpp
```
spline = splinepy.create.box(2,2).bspline
ukvs = spline.unique_knots
kvs_mult = spline.knot_multiplicities
```
> Binding for Knotvector functions

- CONTRIBUTING.md
- splinepy/helpme/create.py
- splinepy/helpme/extract.py
Just some minor modifications to the documentation. Enables `help` calls on `spline.extract.<method>` and proper docs
> Update Documentation in HelpMe Modules

- examples/show_multipatch.py
- splinepy/helpme/extract.py
- splinepy/microstructure/microstructure.py
- splinepy/microstructure/tiles/cross_3d.py
- splinepy/microstructure/tiles/inverse_cross_3d.py
- splinepy/utils/data.py
Some examples are currently not working.
1. FFD [x]
3. microstructure [ ]
5. multipatch [ ]
*  Fix example issues.
> Fix: examples not working

- examples/run_all_examples.py
- examples/show_isophotes_and_curvature.py
- examples/show_multipatch.py
- examples/show_spline_data.py
- splinepy/utils/data.py
- tests/test_arrays.py
This PR wishes to make plotting with callbacks easier. It removes requirement of defining the behavior with the `resolutions` argument.
*  #291 
I wanted to add this query helper to `helpme.create`, but @jzwar mentioned that `helpme.create` is quite exclusively for splines. Would you prefer to have a `helpme.make` to add some non-spline based makings?
> Easier spline data plotting with callbacks

- pyproject.toml
- splinepy/helpme/ffd.py
compatibility bug fix
*  deprecated kwarg
@clemens-fricke can you add ffd test here again?
> remove deprecated kwarg

- examples/iga/collocation_laplace_problem.py
- examples/iga/collocation_laplace_problem_sparse.py
- examples/iga/galerkin_laplace_problem.py
- examples/show_isophotes_and_curvature.py
- examples/show_multipatch.py
- examples/show_spline_data.py
- splinepy/helpme/visualize.py
follow up of tataratat/gustaf#188
*  `data` is clear enough
```python
spline.spline_data["this"] = this_array
spline.show() # shows "this" right away
spline.spline_data["dis"] = dis_array
spline.show_options["data"] = "dis"
spline.show() # shows "dis"
```
> data_name -> data

- splinepy/io/default.py
> update mfem extention

- splinepy/helpme/fit.py
`numpy` throws deprecation warning - now no longer
> Small bugfix

- splinepy/helpme/create.py
- splinepy/helpme/integrate.py
This feature enables the use of integrals in n-dimensions.
```
new, feature = splinepy.tataratat()
```
> Ft nd integrals

- splinepy/helpme/create.py
- splinepy/helpme/integrate.py
- tests/test_volume_integration.py
Integrals on embedded splines using 
```math
\mathcal{J}^S = \big(\text{det}(\mathbf{J}^T\mathbf{J}) \big)^{\frac{1}{2}}
```
Baseline for @j042
> Integrals of parametric functions

- splinepy/microstructure/tiles/__init__.py
- splinepy/microstructure/tiles/cross_3d_linear.py
New tile. In 3D we want to keep the degrees as low as possible!
> Add new linearized tile

- splinepy/helpme/visualize.py
> Mini-PR Linewidth for 1D splines

- src/py/py_multipatch.cpp
We were just lucky that it worked so far. I think this should solve the issue
> Bugfix to compute G1 correctly

- include/splinepy/py/py_multipatch.hpp
- splinepy/multipatch.py
- src/py/py_multipatch.cpp
> Enforce Recomputation of Multipatch Interfaces

- splinepy/microstructure/tiles/cross_3d.py
Also changed the "style" of the connecting interface to ensure c1 continuity between adjacent faces
> Added derivative of cross-tile

- splinepy/helpme/extract.py
- tests/test_extract.py
There was a bug in spline extraction, as you need two different indexing schemes for "single-line" extraction and interval extraction (because in a slice, the last index is non-inclusive).
> Bug in spline extractions

- splinepy/microstructure/microstructure.py
> Bugfix Matrix multiplication

- include/splinepy/py/py_multipatch.hpp
- splinepy/microstructure/tiles/cross_2d.py
- splinepy/multipatch.py
- src/py/py_multipatch.cpp
- tests/test_multipatch.py
Extraction of multipatch boundaries for multipatch on c++ side
* #403
> Bugfix #403

- examples/show_isophotes_and_curvature.py
- include/splinepy/splines/helpers/extract.hpp
- splinepy/io/gismo.py
- src/py/py_knot_insertion_matrix.cpp
- src/splines/helpers/extract.cpp
- tests/test_bezier_extraction.py
Fixed issues when exporting multipatches with `None` as field values. 
* multipatches with `None` in fields raised several errors
> Bf gismo export

- tests/conftest.py
replace `get_*` by hardcoding values.
> remove getters in conftest

- examples/fitting.py
- splinepy/helpme/fit.py
> Fixes multidimensional bug, requires at least numpy version 1.7.0

- src/proximity/proximity.cpp
Mini PR that implements comments of #394.
> finalize #394
