tataratat/splinepy

- src/bezier.hpp
Splinepy did not check the control point size before updating the spline on the python side. It was all my fault and I beg your forgiveness.
> Resizing of control point vector in Python update

- cpp/splinepy/py/py_bezier.hpp
- cpp/splinepy/py/py_rational_bezier.hpp
Repeated order elevations lead to problems in both bezier types. This was due to the update_p routines which lost track of their pointers. It is fixed now. Tested surfaces and lines with up to 25 consecutive order elevations.
> BugFix Order Elevation

- splinepy/_base.py
- splinepy/_spline.py
- splinepy/bezier.py
- splinepy/bspline.py
- splinepy/io/json.py
- splinepy/log.py
- splinepy/nurbs.py
- splinepy/rational_bezier.py
- splinepy/utils.py
This is my first PR, hopefully I'm doing it right...
* [Create own logger class for `splinepy`](https://github.com/tataratat/splinepy/issues/47)
* Moved `configure()` from `splinepy.utils` to `splinepy.log`
* Added `debug()`, `info()` and `warning()` methods in `splinepy.log`
* Added a base class `SplinepyBase` implemented in `_base.py`, which is now the base class for all `splinepy` classes and so far only implements logging functions `logd()`, `logi()` and `logw()` utilizing the functionality provided by `splinepy.log` 
* Changed logging in all other classes to use the functions provided by `SplinepyBase` instead of the native `logging` module
> Add thin logger as demanded by #47

- MANIFEST.in
- pyproject.toml
- setup.py
Enables dynamic build with sdist, in case there's not an appropriate wheels available in pypi.
#48 
More distribution options like `conda` and add CI to build and upload, each time we bump the version
> dynamic sdist build

- cpp/splinepy/fitting/fitting.cpp
- cpp/splinepy/py/py_bezier.hpp
- cpp/splinepy/py/py_bspline.hpp
- cpp/splinepy/py/py_nurbs.hpp
- cpp/splinepy/py/py_rational_bezier.hpp
- cpp/splinepy/py/spline_reader.hpp
- cpp/splinepy/splines/helpers.hpp
- cpp/splinepy/utils/arrays.hpp
This is to deal with issue #43 .
1. There were many warnings when building splinepy, that made the project look very unprofessional. Most of the warnings were related to comparisons between signed and unsigned types. 
2. There were a class member variables used as counters that were very unspecific, called `i` and `j`, which is problematic as it is unclear what the counters are actually referring to.
> Get rid of warning

- cpp/splinepy/proximity/proximity.hpp
- Minor fix regarding kdtree's distance metric. Uses L2 instead of L1.
- Adds aggresive_bounds option, that is currently not used from py-side.
| before | after |
| -- | -- |
| <img width="708" alt="Screenshot 2022-09-01 at 14 56 42" src="https://user-images.githubusercontent.com/47114801/188388501-5f2990da-9ba2-4652-bd95-c2af83390e94.png"> | <img width="700" alt="Screenshot 2022-09-05 at 09 12 24" src="https://user-images.githubusercontent.com/47114801/188389080-9ec9384d-b8db-4671-b41a-1d9d87dd6192.png"> |
- this is a small progress PR of "verbose query"
- no guarantee what so ever for aggressive bounds
- for somewhat complex spline, we need a kdt of very fine samples -> local / weighted resampling that's thread-safe
> Fix initial guess metric

- cpp/splinepy/py/py_bezier.hpp
- cpp/splinepy/py/py_nurbs.hpp
- cpp/splinepy/py/py_rational_bezier.hpp
- tests/test_evaluation.py
*  Related to #32 and #33
Up to this point, derivatives of Bézier splines resulted in new splines, which were a parametric representation of the derivative. In the SplineLib, however, the derivatives are evaluated at specific points with indexed derivates. This functionality has now also been transfered to `bezman` and ultimately added to `splinepy`.
```
deg, dim = 3, 3
derivative = np.random.randint(deg,size=(3))
a = gus.Bezier(degrees=[deg] * 3, control_points=np.random.rand(5**dim,dim))
derivatives = a.derivative(np.random.rand(400,dim), derivative)
```
which calculates the derivative of a random spline.
> Bindings for Derivatives

- splinepy/_base.py
- splinepy/spline.py
Add base type for splinepy. Enables easy and uniform logging for all inherited classes.
```python
class Multipatch(SplinepyBase):
...
def some_func(self):
self._logi("this func is for demo")
self._logd("some_func is called and log is tested")
self._logw("this func doesn't do much")
```
> add splinepybase for python

- CMakeLists.txt
- cpp/splinepy/splines/splinepy_base.cpp
- cpp/splinepy/splines/splinepy_base.hpp
- Adds a warning flag to clang
- Add missing const, so that it matches derived class' implementation
* `SplinepyBase::ExtractDim` couldn't find matching implementation
> Avoid wrong overwrite

- cpp/splinepy/splines/helpers/extract.hpp
- cpp/splinepy/utils/grid_points.hpp
- tests/common.py
- tests/test_extract_boundaries.py
should have only worked for boundaries that are extracted from the highest parametric dimension (e.g., dimension 1 in 2D).
Now there is an additional test so it won't happen again - hopefully
> Bugfix Extract Boundary didn't work properly

- cpp/splinepy/py/init/exporter.cpp
- cpp/splinepy/py/py_spline.hpp
- cpp/splinepy/py/py_spline_exporter.hpp
- cpp/splinepy/splines/bezier.hpp
- cpp/splinepy/splines/bspline.hpp
- cpp/splinepy/splines/helpers/scalar_type_wrapper.hpp
- cpp/splinepy/splines/nurbs.hpp
- cpp/splinepy/splines/rational_bezier.hpp
- cpp/splinepy/splines/splinepy_base.cpp
- cpp/splinepy/splines/splinepy_base.hpp
- examples/basis_and_support.py
- splinepy/io/gismo.py
- splinepy/multipatch.py
- splinepy/spline.py
- tests/test_orientation.py
This PR provides the functionality to determine the orientation in n dimensional space between two adjacent patches
*  #81 
see tests/test_orientation for detailed example
```
a = splinepy.Bezier(
degrees=[1, 1], control_points=[[1, 1], [2, 1], [1, 2], [2, 2]]
)
b = splinepy.Bezier(
degrees=[1, 1], control_points=[[1, 2], [2, 2], [1, 3], [2, 3]]
)
axis_mapping, axis_orientation = splinepy.splinepy_core.get_orientation(a, 3, b, 2, 0.001)
```
It also fully supports gismo export now
> Ft orientation gismo

- cpp/splinepy/fitting/fitting.cpp
Description
As pointed out in issue #99, the current routine `splinepy.BSpline.interpolate_surface` does not allow an unequal number of sampling points. This is due to a wrong ordering of the sampling points in l.85. 
This code fixes this issue and transposes the control points, as they are otherwise incorrectly ordered. I am happy on feedback to improve the efficiency of l.108-114.
*  Issues addressed: #99 
The example illustrated in #99. 
```
import numpy as np
def interpolate_function(f, samples_per_direction):
"""Interpolate the function f with a given number of samples 
in each direction on the interval [-1, 1] x [-1, 1]
Parameters
----------
f : function
Function to interpolate
samples_per_direction : list
Number of samples per direction
Returns
-------
np.ndarray, …
```
> Bugfix: surface interpolation with unequal number of control points

- splinepy/io/json.py
fixes resource warning from json io. Uses context instead of raw `open()`
*  `splinepy/splinepy/io/json.py:30: ResourceWarning: unclosed file <_io.TextIOWrapper name=.....`
> fix ResourceWarning

- cpp/splinepy/py/CMakeLists.txt
- cpp/splinepy/py/init/coordinate_reference.cpp
- cpp/splinepy/py/py_coordinate_references.hpp
- cpp/splinepy/py/py_spline.hpp
- cpp/splinepy/py/splinepy_core.cpp
- cpp/splinepy/splines/bezier.hpp
- cpp/splinepy/splines/bspline.hpp
- cpp/splinepy/splines/nurbs.hpp
- cpp/splinepy/splines/rational_bezier.hpp
- cpp/splinepy/splines/splinepy_base.cpp
- cpp/splinepy/splines/splinepy_base.hpp
- cpp/splinepy/utils/reference.hpp
- splinepy/bspline.py
- splinepy/spline.py
- tests/common.py
- tests/test_property_modification.py
- you can now have direct access to underlying cpp coordinates. Don't really have to use it all the time, but if you have a certain operation that uses high dim / high order splines, and need to change only control points, this may save you some time.  Doesn't support inplace operations. 
- Only create local trackable copies on demand. sometimes, there are times where we never need them
- add small set of test utils in tests/common.py
*  there are some use cases where cps change a lot, but this always recreates core spline and for complex splines, that's expensive (especially with the approach of SplineLib's creation).
* copied properties would always have modified flags
> CoordinateReferences

- splinepy/utils/data.py
- tests/test_cartesian.py
Adds a function for [cartesian product](https://en.wikipedia.org/wiki/Cartesian_product) as well as a version that performs reversed version of the product. Adapted from a [stackoverflow](https://stackoverflow.com/questions/11144513/cartesian-product-of-x-and-y-array-points-into-single-array-of-2d-points/49445693#49445693)'s discussion.
```python
>>> import numpy as np
>>> import splinepy
>>> a = np.array([0,.5,1])
>>> splinepy.utils.data.cartesian_product((a,a))
array([[0. , 0. ],
[0.5, 0. ],
[1. , 0. ],
[0. , 0.5],
[0.5, 0.5],
[1. , 0.5],
[0. , 1. ],
[0.5, 1. ],
[1. , 1. ]])
```
> add cartesian prod

- setup.py
- splinepy/__init__.py
- splinepy/helpme/__init__.py
- splinepy/helpme/multi_index.py
- splinepy/spline.py
- tests/test_multi_index.py
Adds `MultiIndex` class that helps to find global ids for data that's sequentially listed, but actually representing grid-like structure. In other words, helps find control point ids using numpy's `__getitem__` syntax. name multi_index is motivated by numpy's function [np.ravel_multi_index](https://numpy.org/doc/stable/reference/generated/numpy.ravel_multi_index.html#numpy.ravel_multi_index). This way you don't have to use `%` or `//`.  
Also, as discussed, added `helpme` module. Will be a place to implement functions that helps some uses cases with splines. This means some of the functions / classes implemented in `spline.py` will be moved there in next PR. It won't change any behavior of `Spline` class.
*  Easy access to global control point ids (raveled index) wanted
A short / …
> helpme & multi index 

- cpp/splinepy/py/py_spline.hpp
- splinepy/spline.py
In applications, you probably need to evaluate basis quite a few times. However, support doesn't change within the same parametric spaces. This provides a separate call.
*  We always get support. Too much support
```python
...
support = spline.support(queries)
basis = spline.basis(queries)
basis_der = spline.basis_derivatives(queries, query_orders)
```
> add separate calls for basis, support, basis_deriavtive

- cpp/splinepy/splines/helpers/extract.hpp
Creating boundary spline can be expensive for BSpline Families, as it will recreate the basis functions. This PR avoids it by just taking pointers to existing data structures (they are already shared_ptrs) for boundary spline. Much cheaper. Will possibly use boundaries to plot in gustaf rather than organized queries.
*  Maybe expensive to extract boundaries.
> use RemoveOneParametricDimension() for slicing

- splinepy/io/__init__.py
- splinepy/io/iges.py
- splinepy/io/ioutils.py
- splinepy/io/irit.py
- splinepy/io/xml.py
Some of the io routines returned dictionaries of spline data and others returned splines. Now no longer.
Also - save input for irit files
> Uniform return types in IO

- cpp/splinepy/py/py_spline_extensions.hpp
- cpp/splinepy/py/py_spline_list.hpp
- cpp/splinepy/splines/rational_bezier.hpp
- cpp/splinepy/splines/splinepy_base.cpp
- tests/test_spline_list.py
* Adds `compose` and `composition_derivative` to list functions.
* `cartesian_product` option is added to avoid nested for loop. 
* Adds `NThreadQueryType` option to `NThreadExecution` to support "step" execution 
* fixes #148
* fixes #152
WIP - bindings and tests .......
* slow to loop in python
```python
from splinepy.splinepy_core import lists
outer_splines = [<list-of-splines0>]
inner_splines = [<list-of-splines1>]
composed = lists.compose(outer_splines, inner_splines, cartesian_product=True, nthreads=300)
assert len(composed) = len(outer_splines) * len(inner_splines)
```
> Ft list compose

- .pre-commit-config.yaml
- README.md
The example (Quick Start) in the README.md file no longer worked. There were typos and other errors. These bugs have been fixed here. 
Since pre-commit didn't work for me, I downgraded mirrors-clang-formats to 15.0.7
*  #155
> Update README.md file

- tests/test_multi_index.py
reduce max random sample value for `multi_index` test. 
*  sampling big numbers would result in giant memory space for test arrays, which breaks ci runs
> reduce randint max

- cpp/splinepy/py/py_spline.hpp
- splinepy/spline.py
There were duplicating typename `CoreSpline`. It means:
- in python -> `splinepy::py::PySpline`
- in cpp -> `std::shared_ptr<splinepy::splines::SplinepyBase>`
Now, in python `CoreSpline` is renamed to `PySpline` to avoid confusion.
> Clean up - Rename CoreSpline to PySpline

- cpp/splinepy/py/init/reader.cpp
- cpp/splinepy/py/py_spline_reader.hpp
Changed two things in `cpp/splinepy/py/py_spline_reader.hpp`:
- function names to fit C++ convention (e.g. from `read_xml` to `ReadXml`) and 
- If elses in `ParseBspline` and `ParseNurbs` to switches
> Cu pyreader

- splinepy/bezier.py
- splinepy/bspline.py
- splinepy/microstructure/microstructure.py
- splinepy/nurbs.py
This is more readable and avoids copy bugs. Transformation operations should always end in copies of the original, regardless of whether the type was changed or not
> Copy of C++ spline lead to 2 splines sharing core

- splinepy/io/gismo.py
- splinepy/multipatch.py
- src/py/py_multipatch.cpp
- tests/test_gismo.py
- tests/test_multipatch.py
Up to this point, interfaces were stored in the `mrng`-style. This had two major downfalls. 
1. The adjacent face ID had to be calculated separately
2. The adjacent face ID was not uniquely identifiable if more than one intersection existed with the same patch.
These issues can be solved if the interfaces do not refer to the neighboring patch ID, but rather to the neighboring face ID in the global counting system.
*  Issue was communicated via Rocket.Chat
> Change numbering system of interfaces

- splinepy/multipatch.py
There was an issue in `Multipatch->set_boundary()`, where an exception was shadowed by another catch block which led to unhelpful output messages.
> Tiny bugfix

- splinepy/bspline.py
- splinepy/helpme/create.py
- tests/common.py
- tests/test_creator.py
add conform flag to parametric_view. then resulting spline has conforming parametric space and cps are placed on parametric space "box". Expected use case is in interactive mode, where you can set boundary conditions based on difference in control point locations in parametric view. Added test
Also fixes some errors in create
*  wrong scaling in `from_bounds()`
> add conform flag to parametric_view

- splinepy/microstructure/microstructure.py
show_microstructure.py caused TypeError
```bash
Traceback (most recent call last):
File "splinepy/examples/show_microstructures.py", line 28, in <module>
ms = generator.create(macro_sensitivities=True)
File "splinepy/splinepy/microstructure/microstructure.py", line 633, in create
cps = np.hstack(p.cps for p in patch_info)
File "lib/python3.10/site-packages/numpy/core/shape_base.py", line 216, in _vhstack_dispatcher
return _arrays_for_stack_dispatcher(tup)
File "lib/python3.10/site-packages/numpy/core/shape_base.py", line 209, in _arrays_for_stack_dispatcher
raise TypeError('arrays to stack must be passed as a "sequence" type '
TypeError: arrays to stack must be passed as a "sequence" type such as list or tuple.
```
> fix microstructure

- splinepy/__init__.py
often, I need to import gustaf separately just to use `gus.show()` let's save that step
```python
splinepy.show(splinepy.helpme.create.surface_circle(12), splinepy.helpme.create.box(1,2,3))
```
> add shortcut to gus.show

- .github/workflows/main.yml
updates pypi [publish method](https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/) as mentioned in tataratat/napf#21. Thanks @carlosal1015!
> switch to trusted publisher

- README.md
Fixed a small issue in the `README.md` file, where the installation of splinepy with all dependencies was displayed a little misleadingly as 
```bash
pip install splinepy[all]
```
while this for instance does not work on the Mac shell. Instead, it will now be displayed as
```bash
pip install "splinepy[all]"
```
which should work both on Mac and other OS.
> Add quotation marks around splinepy[all]

- .github/workflows/test.yml
- CMakeLists.txt
- include/splinepy/py/py_spline_extensions.hpp
- src/py/py_spline_extensions.cpp
- src/splines/splinepy_base.cpp
- fixes unused function warning use by making the function `static inline`. 
- adds `Werror` to `--enable_warning`
> fix unused function warning

- src/explicit/CMakeLists.txt
make splinepy::explicit object target.
Otherwise this will have to be a circular dependency.
> fix shared lib build

- .pre-commit-config.yaml
- pyproject.toml
- splinepy/io/gismo.py
- splinepy/spline.py
Move the configuration of the tools used in our pre-commit to the `pyproject` file. This will enable us to have more consistent results running these tools outside the pre-commit environment.
The tools will look for a possible configuration in the `pyproject` file therefore, if we configure them there the configuration is consistent between different invocations of these tools.
*  configuration differs when running a tool defined in the pre-commit on its own without invoking pre-commit.
* Configuration can only be read in if the package `tomli` is installed. I have added the need for this package to the pre-commit configuration, but if a tool is invoked on its own, the user might (depended on the python version/package is installed due to other dependencies) need to install the package …
> Add: Move configurations from precommit to  pyproject.toml.

- .github/workflows/docs.yml
- docs/source/conf.py
Sphinx writes a warning that in the next release the default value for `navigation_with_keys` will change to `False`. Because in the docs/ .. pipeline the flag for `Warning, treated as an error` is set to `True` (-W): (`sphinx-build -W -b html docs/source docs/build -j auto`)  the pipeline fails.
#281 
```
new, feature = splinepy.tataratat()
```
> Bug fix ci docs

- include/splinepy/proximity/proximity.hpp
- include/splinepy/splines/helpers/extract.hpp
- include/splinepy/utils/grid_points.hpp
- src/py/py_multipatch.cpp
- src/py/py_spline.cpp
This PR removes `GridPoints` - It was only used to extract hyperplane ids.  CStyleArrayGridPoints is renamed to GridPoints. 
*  dim as template parameter
> make CStyleArrayGridPoints GridPoints

- include/splinepy/proximity/proximity.hpp
- include/splinepy/splines/bezier.hpp
- include/splinepy/splines/bezier.inl
- include/splinepy/splines/bspline.hpp
- include/splinepy/splines/helpers/extract.hpp
- include/splinepy/splines/helpers/scalar_type_wrapper.hpp
- include/splinepy/splines/nurbs.hpp
- include/splinepy/splines/rational_bezier.hpp
- include/splinepy/splines/rational_bezier.inl
- include/splinepy/utils/arrays.hpp
- include/splinepy/utils/grid_points.hpp
- src/py/py_multipatch.cpp
- src/py/py_spline.cpp
This PR contributes to the long term goal of removing para_dim/dim from template parameters.
Proximity was taking SplineType as a template parameter.
Then it uses kParaDim and kDim to create std::arrays, nested std::arrays, and kdtree.
A solution for std::arrays is to add an Array class - this results updates in utils/arrays.hpp
As for k-d tree, turns out,  dim is not a strict template parameter. So I've updated napf to accordingly.
This should also reduce some compile tile.
- split .cpp file
- currently, `clipped` info is not used. It used to be part of solver's skip_mask.
*  Missing flexibility in Proximity
> tparam-free proximity

- include/splinepy/proximity/proximity.hpp
- include/splinepy/utils/nthreads.hpp
- src/py/py_multipatch.cpp
- src/py/py_spline.cpp
The "nthreads.hpp"-file of splinepy has been changed and the inherent files have been adapted as well. Goal was to eliminate the distinction between "Steps" and "Chunks" inside the "nthreads.hpp"-file.
Reference to this topic is this [issue](https://github.com/tataratat/splinepy/discussions/251#discussion-5636315).
*  reduced the lamda signature of NThreadExecution to 3 parameters
*  deleted the distinction between Chunks and Steps
*  adapted all the function calls
```
void NThreadExecution(const Func& f, const IndexType& total, IndexType nthread)  {
// ...
// f hands over 3 parameters now (instead of 2)
f(begin, end, thread_index);
// ...}
```
> New_NThreadExe

- examples/show_multipatch.py
- splinepy/microstructure/tiles/crosstile3d.py
- splinepy/microstructure/tiles/inversecrosstile3d.py
- splinepy/utils/data.py
- numpy stack now requires list or tuple 
- tile return value mistake (was put into double twice)
- resolution in multipatch is integer which caused issue
> Fix remaining two examples

- splinepy/io/iges.py
- tests/test_iges.py
iges export now checks parametric dimension of spline, if it is 3, then a value error is raised and a suggestion for a solution is presented
*  solved issue #272
calling the example from the issue now gives the following error:
```
ValueError                                Traceback (most recent call last)
[c:\Users\mkofler\miniconda3\envs\splinepy_dev\Lib\site-packages\splinepy\microstructure_fix.ipynb](file:///C:/Users/mkofler/miniconda3/envs/splinepy_dev/Lib/site-packages/splinepy/microstructure_fix.ipynb) Cell 3 line 1
[13](vscode-notebook-cell:/c%3A/Users/mkofler/miniconda3/envs/splinepy_dev/Lib/site-packages/splinepy/microstructure_fix.ipynb#W0sZmlsZQ%3D%3D?line=12) microstructure.microtile = getattr(sp.microstructure.tiles, "NutTile3D")().create_tile()[0] …
```
> added export check to splinepy/io/iges.py

- pyproject.toml
Using `scikit-build-core` allows us to distribute static libraries as well. This results in giant files. Setting `install.strip=true` reduces size, so this PR does that. I will maybe remove `3.7` wheels as well.
*  Giant binary
> strip binary

- include/splinepy/proximity/proximity.hpp
- splinepy/spline.py
- src/CMakeLists.txt
- src/proximity/proximity.cpp
- src/py/py_spline.cpp
splits proximity.hpp to headers and source. Should take less time to compile
> split proximity hpp / cpp

- splinepy/spline.py
- src/py/py_spline.cpp
- tests/test_evaluation.py
Implements #248
*  #248
```python
import numpy as np
q = np.random.random((10000, spline.para_dim))
assert np.allclose(
spline.jacobian(q),
spline.derivative(q, np.eye(spline.para_dim)).transpose(0, 2, 1)
)
```
> accept any number of order-queries for derivatives

- splinepy/helpme/create.py
- splinepy/helpme/visualize.py
This PR incorporates changes in tataratat/gustaf#171
and fixes #323
> remove _backend layer - match gustaf's #171

- src/py/py_spline.cpp
Fixes #307. By switching the order of state unpacking. @clemens-fricke could you please check if this fixes the issue?
*  bspline pickle fails
> change pickle unpacking order

- splinepy/helpme/check.py
- splinepy/helpme/create.py
- splinepy/helpme/extract.py
- splinepy/helpme/ffd.py
- splinepy/helpme/integrate.py
- splinepy/spline.py
to avoid circular reference, we keep weakref of the helpee within helpers. See tataratat/gustaf#185.
Turns out, keeping everything weakref doesn't allow "chained"-one-line uses. So, we will just create helpers that don't have states on the fly. Ones that have states will use weakref - they are okay, since we won't use them in "chained"-one-lines.
*  fixed #327
> helpers use weakref

- splinepy/helpme/create.py
- splinepy/helpme/extract.py
- tests/test_extract.py
adds arrow_data extraction that respects show_options. There are times, where you want to just get data_origin, and arrow_end
*  Want arrows only, please
```python
spline.spline_data["me"] = spp.SplineDataAdapter(spline, locations=np.random.random((10,10)))
edges = spline.extract.arrow_data("me")
begin_and_ends = edges.vertices[edges.edges]
print(begin_and_ends.shape)
```
> add extract.arrow_data

- splinepy/io/gismo.py
Field output is not in the usual gismo standard and only works together with [pygadjoint](https://github.com/tataratat/pygadjoints/tree/main) so I decided to extend the export functionality a little more.
*  Macro spline optimization sometimes only applies to a subset of all macro-spline ctps
@j042 I need this for optimisations only. I can have it on a separate branch for all eternity if you prefer. Also relevant for @kkILSB
> Selective Field Output in G+smo

- CONTRIBUTING.md
- splinepy/helpme/check.py
- splinepy/helpme/create.py
- splinepy/helpme/extract.py
- splinepy/helpme/integrate.py
Instead of grabbing onto `__docs__`, this PR uses built-in functools to document helper functions.
*  aesthetics
> update documentation method for helpers

- splinepy/helpme/create.py
- tests/test_creator.py
Embedding into a higher dimension. Can also strip coordinate dimensions (always the last)
```
import splinepy as spp
rectangle = spp.helpme.create.box(1,2)
rectangle_in_4d = rectangle.create.embedded(4)
```
> Embedded Splines

- .github/workflows/main.yml
- pyproject.toml
Reverting part of #364, where we only install `PythonModule`. For local builds, it is very convenient to have them installed (at least for my use case). For wheel builds and distribution, we keep this to reduce wheel size. We can perhaps set a specific version of python and add all the targets only for that one.
*  Need all components for local use
> revert default only-python-install

- splinepy/utils/data.py
- tests/test_property_modification.py
using numpy's ufunc, PhysicalSpaceArray won't sync afterward. Now they do.
*  `np.add(spline.cps, values, out=spline.cps)` won't sync core control points
> add __array_wrap__

- tests/test_svg.py
base64 test always gives error due to inconsistent versions and compression. We just throw warning for that instead of error.
*  local test always fails, but results have no qualitative difference
> mute local svg test

- include/splinepy/utils/arrays.hpp
- src/proximity/proximity.cpp
The indices of the solution vector do not change as the pivoting only affects the rows of the matrix and the lhs, but not the solution (columns remain unchanged).
@j042, please verify
*  #385
> Bugfix - Wrong indices for back substitution

- include/splinepy/py/py_multipatch.hpp
- splinepy/io/gismo.py
- splinepy/multipatch.py
- src/py/py_multipatch.cpp
- tests/test_orientation.py
Interface orientations were always computed on the fly... What a waste. I wanted to have them available in case we ever decide to check the conformity...
> Interface Orientations were not available

- examples/show_basis.py
- splinepy/helpme/create.py
- splinepy/helpme/extract.py
- splinepy/spline.py
Visualizing basis is easier now. `spline.extract.bases()` will create a spline that represents the basis function. This isn't the most efficient way, but fits right into our current visualization and helpers pipeline.
Some sort of automatic random coloring could be a nice add-on.
*  Visualizing basis was not easy.
```python
bases = spline.extract.bases()
spp.show(bases)
support123 = spline.extract.bases([1, 2, 3])
spp.show(support123)
```
> Ft extract basis

- .github/workflows/docs.yml
- .github/workflows/main.yml
- .github/workflows/test.yml
- .github/workflows/test_full.yml
- pyproject.toml
Installing splinepy non-editable mode would cause import issues. Mainly due to the compiled module, as it is not located in local directory. As stated in [pytest doc](https://docs.pytest.org/en/stable/explanation/pythonpath.html), this PR takes `append` mode for pytest to prefer installed packaged.
*  failed local / CI test calls
> fix pytest import issue

- include/splinepy/py/py_spline_extensions.hpp
- include/splinepy/splines/bezier.hpp
- include/splinepy/splines/bezier.inl
- include/splinepy/splines/bspline.hpp
- include/splinepy/splines/helpers/scalar_type_wrapper.hpp
- include/splinepy/splines/nurbs.hpp
- include/splinepy/splines/rational_bezier.hpp
- include/splinepy/splines/rational_bezier.inl
- include/splinepy/splines/splinepy_base.hpp
- include/splinepy/utils/arrays.hpp
- src/py/py_spline.cpp
- src/py/py_spline_extensions.cpp
- src/splines/splinepy_base.cpp
- tests/test_kv_manipulation.py
- bump pybind version
- update bsplinelib - avoids using ReallocateInsert. Instead reallocate once at the beginning and insert to the same buffer
- update splinepy to pass multiplicity info to bsplinelib. This doesn't change python API. all unique/multiplicity/return values are manages in cpp. Regarding return value check, test will be added
- Add test for knot insertion result check
> Update third party

- splinepy/microstructure/microstructure.py
fixes a bug where the construction of the support and anti-support lists for two dimensional para_sensitivities would not work properly
example `show_microstructures` looks good/unaltered.
> bf for support construction for multiple para-sensitivities

- docs/markdown/spline_intro.md
In the documentation "Introduction to Splines", it fixes issues with subscripts and brackets. Additionally, some minor changes to the text like a missing hyphen are made.
> Fix typesetting issues in documentation "Introduction to Splines"

- .clang-format
- .github/workflows/docs.yml
- .github/workflows/main.yml
- .github/workflows/test.yml
- .github/workflows/test_full.yml
- .github/workflows/test_wheels.yml
Update the CI/CD actions. Some are deprecated and now start to throw errors.
We can think about adding something like Dependabot to keep track of these actions?
*  Workflow does not work
* - Documentations are up-to-date.
* - Added example(s)
* - Added test(s)
> Actions version bump

- splinepy/helpme/visualize.py
Adding `arrow_data_to_origin` option added from gustaf-v0.1.0 to a copy list. This is a non-raising copy, so won't effect older versions. However, maybe good to add a warning log in gustaf
> Add missing option copy
